server:
  port: 80
  

#-SpringBoot整合Mybatis相關配置
spring:
  datasource:
    url: jdbc:mysql://192.168.1.189:3306/finweb?characterEncoding=utf-8&serverTimezone=UTC
    username: maxe0701
    password: Love1025
    driver-class-name: com.mysql.cj.jdbc.Driver
#-AOP動態代理修改：配置路徑( spring.aop.proxy-target-class )
#-1.配置預設為 true  ( 使用 cglib動態代理 )
#-2.配置修改為 false ( 使用 jdk動態代理 )
  aop:
    proxy-target-class: false
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml  #-mapper映射文件路徑(預設路徑為：resources/)
  type-aliases-package: com.kulu.domain  #-配置哪個package下的class(java bane)有默認的別名